Repository imhardikdesai/news-website, pull requests merged in 2024-10, with the labels that each got.

#12 fixed infinite loader
  app.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#14 fixed current year value in footer
  app.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#15 Fixed image stretch issue.
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#19 fix: Fixed the dark mode UI
  style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#16 Effects on newsCards
  style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest
